#!/usr/bin/env python3
"""Build every derived artifact from tokens/tokens.json (the single source of truth).

Outputs (all inside tokens/):
  tokens.css            CSS custom properties  (LP / HTML slides / HTML banners)
  tailwind.preset.cjs   Tailwind preset        (LP built with Tailwind)
  tokens.py             Python dict            (pptx / docx / xlsx / PIL generators)
  tokens.scss           SCSS variables
  contrast.md           WCAG contrast matrix for every text/background pair
  palette.txt           one hex per line (used by lint_tokens.py)

It also re-derives every non-primary color from its recipe and fails loudly if a
hand-edited hex drifted from the recipe. Run it after any tokens.json change:

    python3 scripts/build_tokens.py            # build + verify
    python3 scripts/build_tokens.py --resolve  # print what the recipes evaluate to
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from colorlib import contrast, hsl, mix, norm_hex, wcag_level  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
TOK = ROOT / "tokens" / "tokens.json"


def load() -> dict:
    return json.loads(TOK.read_text(encoding="utf-8"))


def flat_colors(t: dict) -> dict[str, dict]:
    """name -> color entry, for every color group."""
    out = {}
    for group, entries in t["color"].items():
        for name, entry in entries.items():
            out[name] = dict(entry, group=group)
    return out


def resolve_recipe(recipe: dict, table: dict[str, dict]) -> str:
    kind = recipe["op"]
    if kind == "mix":
        a = recipe["a"] if recipe["a"].startswith("#") else table[recipe["a"]]["hex"]
        b = recipe["b"] if recipe["b"].startswith("#") else table[recipe["b"]]["hex"]
        return mix(a, b, recipe["t"])
    if kind == "hsl":
        return hsl(recipe["h"], recipe["s"], recipe["l"])
    if kind == "alias":
        return table[recipe["of"]]["hex"]
    raise ValueError(f"unknown recipe op {kind}")


def verify(t: dict) -> list[str]:
    errors = []
    table = flat_colors(t)
    for name, entry in table.items():
        if "recipe" in entry:
            want = resolve_recipe(entry["recipe"], table)
            if norm_hex(entry["hex"]) != want:
                errors.append(f"{name}: hex {entry['hex']} but recipe gives {want}")
        elif "source" not in entry:
            errors.append(f"{name}: primary color without a `source` provenance field")
    return errors


def build_css(t: dict) -> str:
    lines = [
        "/* GENERATED by scripts/build_tokens.py from tokens/tokens.json. Do not edit by hand. */",
        f"/* {t['meta']['brand']} design tokens v{t['meta']['version']} */",
        "/* Self-hosted fonts (scripts/fetch_fonts.py). Copy assets/fonts next to this file's parent when shipping. */",
        '@import url("../assets/fonts/fonts.css");',
        ":root {",
    ]
    for group, entries in t["color"].items():
        lines.append(f"  /* color.{group} */")
        for name, e in entries.items():
            lines.append(f"  --ml-{name}: {e['hex']};")
    ty = t["typography"]
    lines.append("  /* typography */")
    lines.append(f"  --ml-font-sans: {ty['families']['sans']['css']};")
    lines.append(f"  --ml-font-mono: {ty['families']['mono']['css']};")
    lines.append(f"  --ml-font-display: {ty['families']['display']['css']};")
    for k, v in ty["scale_px"].items():
        lines.append(f"  --ml-fs-{k}: {v}px;")
    for k, v in ty["leading"].items():
        lines.append(f"  --ml-lh-{k}: {v};")
    for k, v in ty["tracking_em"].items():
        lines.append(f"  --ml-ls-{k}: {v}em;")
    lines.append("  /* spacing (4pt rhythm) */")
    for k, v in t["space_px"].items():
        lines.append(f"  --ml-sp-{k}: {v}px;")
    lines.append("  /* radius */")
    for k, v in t["radius_px"].items():
        lines.append(f"  --ml-r-{k}: {v}px;")
    lines.append("  /* border / shadow */")
    for k, v in t["border"].items():
        lines.append(f"  --ml-bw-{k}: {v}px;")
    for k, v in t["shadow"].items():
        lines.append(f"  --ml-shadow-{k}: {v};")
    lines.append("}")
    lines.append("")
    lines.append("/* Google Fonts import (self-host in production; see references/typography.md) */")
    lines.append(f"/* @import url('{ty['google_fonts_url']}'); */")
    return "\n".join(lines) + "\n"


def build_scss(t: dict) -> str:
    lines = ["// GENERATED by scripts/build_tokens.py. Do not edit by hand."]
    for group, entries in t["color"].items():
        for name, e in entries.items():
            lines.append(f"$ml-{name}: {e['hex']};")
    for k, v in t["space_px"].items():
        lines.append(f"$ml-sp-{k}: {v}px;")
    return "\n".join(lines) + "\n"


def build_tailwind(t: dict) -> str:
    colors = {}
    for group, entries in t["color"].items():
        for name, e in entries.items():
            colors[name] = e["hex"]
    ty = t["typography"]
    preset = {
        "theme": {
            "extend": {
                "colors": {"ml": colors},
                "fontFamily": {
                    "sans": ty["families"]["sans"]["stack"],
                    "mono": ty["families"]["mono"]["stack"],
                    "display": ty["families"]["display"]["stack"],
                },
                "fontSize": {k: f"{v}px" for k, v in ty["scale_px"].items()},
                "spacing": {k: f"{v}px" for k, v in t["space_px"].items()},
                "borderRadius": {k: f"{v}px" for k, v in t["radius_px"].items()},
            }
        }
    }
    body = json.dumps(preset, ensure_ascii=False, indent=2)
    return (
        "// GENERATED by scripts/build_tokens.py from tokens/tokens.json. Do not edit by hand.\n"
        "// usage: module.exports = { presets: [require('./tailwind.preset.cjs')], ... }\n"
        f"module.exports = {body};\n"
    )


def build_py(t: dict) -> str:
    colors = {n: e["hex"] for _, es in t["color"].items() for n, e in es.items()}
    rgb = {n: tuple(int(e["hex"][i : i + 2], 16) for i in (1, 3, 5)) for n, e in
           ((n, e) for _, es in t["color"].items() for n, e in es.items())}
    ty = t["typography"]
    return (
        '"""GENERATED by scripts/build_tokens.py. Do not edit by hand.\n\n'
        "Import this from python-pptx / python-docx / openpyxl / PIL generators so that\n"
        "office documents and raster banners use exactly the same values as the web.\n"
        '"""\n'
        f"HEX = {json.dumps(colors, ensure_ascii=False, indent=4)}\n"
        f"RGB = {json.dumps(rgb, ensure_ascii=False, indent=4)}\n"
        f"FONT_SANS = {ty['families']['sans']['name']!r}\n"
        f"FONT_MONO = {ty['families']['mono']['name']!r}\n"
        f"FONT_DISPLAY = {ty['families']['display']['name']!r}\n"
        f"FONT_SANS_OFFICE_FALLBACK = {ty['families']['sans']['office_fallback']!r}\n"
        f"SCALE_PX = {json.dumps(ty['scale_px'])}\n"
        f"SPACE_PX = {json.dumps(t['space_px'])}\n"
        f"RADIUS_PX = {json.dumps(t['radius_px'])}\n"
        f"CMYK = {json.dumps({n: e['cmyk'] for _, es in t['color'].items() for n, e in es.items() if 'cmyk' in e})}\n"
    )


def build_contrast(t: dict) -> str:
    table = flat_colors(t)
    bgs = t["contrast"]["backgrounds"]
    fgs = t["contrast"]["foregrounds"]
    lines = [
        "# Contrast matrix (WCAG 2.2, generated)",
        "",
        "Ratio and the strictest text level it satisfies. `AA-large` means 24px+ regular or 18.66px+ bold, "
        "and is also the bar for icons, borders and chart marks. `fail` means never use as text on that background.",
        "",
        "| fg \\ bg | " + " | ".join(f"{b} `{table[b]['hex']}`" for b in bgs) + " |",
        "|---|" + "---|" * len(bgs),
    ]
    for f in fgs:
        cells = []
        for b in bgs:
            r = contrast(table[f]["hex"], table[b]["hex"])
            cells.append(f"{r} {wcag_level(r)}")
        lines.append(f"| **{f}** `{table[f]['hex']}` | " + " | ".join(cells) + " |")
    lines += ["", "## Approved text pairs (>= 4.5 for body, >= 3 for large/bold)", ""]
    for f in fgs:
        for b in bgs:
            r = contrast(table[f]["hex"], table[b]["hex"])
            if r >= 3:
                lines.append(f"- `{f}` on `{b}`: {r} ({wcag_level(r)})")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    t = load()
    table = flat_colors(t)
    if "--resolve" in argv:
        for name, e in table.items():
            if "recipe" in e:
                print(f"{name:14s} {resolve_recipe(e['recipe'], table)}   (json says {e['hex']})")
        return 0
    errs = verify(t)
    if errs:
        print("tokens.json is inconsistent:")
        for e in errs:
            print("  -", e)
        return 1
    out = ROOT / "tokens"
    (out / "tokens.css").write_text(build_css(t), encoding="utf-8")
    (out / "tokens.scss").write_text(build_scss(t), encoding="utf-8")
    (out / "tailwind.preset.cjs").write_text(build_tailwind(t), encoding="utf-8")
    (out / "tokens.py").write_text(build_py(t), encoding="utf-8")
    (out / "contrast.md").write_text(build_contrast(t), encoding="utf-8")
    (out / "palette.txt").write_text(
        "\n".join(sorted({e["hex"].upper() for e in table.values()})) + "\n", encoding="utf-8"
    )
    print(f"built {len(table)} colors -> tokens.css, tokens.scss, tailwind.preset.cjs, tokens.py, contrast.md, palette.txt")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
