#!/usr/bin/env python3
"""Self-host the token fonts: download Noto Sans JP (variable 400-900) and IBM Plex Mono
from Google Fonts into assets/fonts/ and write assets/fonts/fonts.css with local @font-face rules.

Why: sandboxes and some client PCs cannot reach fonts.googleapis.com, and Chromium then
silently falls back to whatever CJK font is installed (WenQuanYi, MS Gothic...). A proposal
rendered that way looks nothing like the reference deck. Bundling the files makes every
render identical everywhere.

    python3 scripts/fetch_fonts.py          # (re)download and rewrite fonts.css
    python3 scripts/fetch_fonts.py --check  # just report what is bundled

Google serves the variable font as ~120 unicode-range woff2 slices (about 4 MB total),
which is far smaller than the 5 MB-per-weight static TTFs.
"""
from __future__ import annotations

import hashlib
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "fonts"
UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36"
FAMILIES = [
    "family=Noto+Sans+JP:wght@400..900",
    "family=IBM+Plex+Mono:wght@500;600;700",
]
CSS_URL = "https://fonts.googleapis.com/css2?" + "&".join(FAMILIES) + "&display=swap"


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def main(argv: list[str]) -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    if "--check" in argv:
        files = sorted(OUT.glob("*.woff2"))
        print(f"{len(files)} font files, {sum(f.stat().st_size for f in files)/1e6:.1f} MB, fonts.css={'yes' if (OUT/'fonts.css').exists() else 'no'}")
        return 0
    css = fetch(CSS_URL).decode("utf-8")
    blocks = re.findall(r"@font-face\s*\{[^}]*\}", css)
    print(f"{len(blocks)} @font-face blocks from Google Fonts")
    total = 0
    out_css = ["/* GENERATED by scripts/fetch_fonts.py. Self-hosted token fonts. Do not edit by hand. */"]
    for b in blocks:
        m = re.search(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", b)
        if not m:
            continue
        url = m.group(1)
        name = hashlib.sha1(url.encode()).hexdigest()[:12] + Path(url).suffix
        dest = OUT / name
        if not dest.exists():
            dest.write_bytes(fetch(url))
        total += dest.stat().st_size
        out_css.append(b.replace(url, name))
    (OUT / "fonts.css").write_text("\n".join(out_css) + "\n", encoding="utf-8")
    print(f"wrote {OUT/'fonts.css'} ({total/1e6:.1f} MB of font data)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
