// GENERATED by scripts/build_tokens.py from tokens/tokens.json. Do not edit by hand.
// usage: module.exports = { presets: [require('./tailwind.preset.cjs')], ... }
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "ml": {
          "brand-teal": "#00979C",
          "brand-yellow": "#F9BB00",
          "brand-black": "#000000",
          "brand-white": "#FFFFFF",
          "teal-50": "#EBF7F7",
          "teal-100": "#D6EEEF",
          "teal-200": "#A3DADB",
          "teal-300": "#70C5C8",
          "teal-400": "#38AEB2",
          "teal-500": "#00979C",
          "teal-600": "#008085",
          "teal-700": "#006A6D",
          "teal-800": "#004C4E",
          "teal-900": "#002A2C",
          "yellow-50": "#FEF8E6",
          "yellow-100": "#FEF1CC",
          "yellow-200": "#FDE499",
          "yellow-500": "#F9BB00",
          "yellow-600": "#D9A300",
          "yellow-700": "#B38700",
          "ink": "#1C2122",
          "sub": "#657A7B",
          "muted": "#94A7A8",
          "line": "#DDE3E3",
          "bg": "#F4F6F6",
          "paper": "#FFFFFF",
          "success": "#008085",
          "warning": "#B38700",
          "danger": "#D8472B",
          "info": "#006A6D",
          "mascot-teal": "#1E8C86",
          "mascot-teal-mid": "#31ACA2",
          "mascot-teal-light": "#87C0B9",
          "mascot-belly": "#D9E2DC",
          "mascot-navy": "#1B2750",
          "mascot-yellow": "#FEDB3C"
        }
      },
      "fontFamily": {
        "sans": [
          "Zen Kaku Gothic New",
          "Hiragino Sans",
          "Hiragino Kaku Gothic ProN",
          "Yu Gothic",
          "Noto Sans JP",
          "sans-serif"
        ],
        "mono": [
          "IBM Plex Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "monospace"
        ],
        "display": [
          "Poppins",
          "Zen Kaku Gothic New",
          "sans-serif"
        ]
      },
      "fontSize": {
        "xs": "12px",
        "sm": "14px",
        "base": "16px",
        "md": "18px",
        "lg": "20px",
        "xl": "24px",
        "2xl": "30px",
        "3xl": "36px",
        "4xl": "48px",
        "5xl": "64px"
      },
      "spacing": {
        "1": "4px",
        "2": "8px",
        "3": "12px",
        "4": "16px",
        "5": "20px",
        "6": "24px",
        "8": "32px",
        "10": "40px",
        "12": "48px",
        "16": "64px",
        "20": "80px",
        "24": "96px",
        "32": "128px"
      },
      "borderRadius": {
        "none": "0px",
        "sm": "4px",
        "md": "8px",
        "lg": "16px",
        "pill": "999px"
      }
    }
  }
};
