"""GENERATED by scripts/build_tokens.py. Do not edit by hand.

Import this from python-pptx / python-docx / openpyxl / PIL generators so that
office documents and raster banners use exactly the same values as the web.
"""
HEX = {
    "brand-teal": "#00979C",
    "brand-yellow": "#F9BB00",
    "brand-black": "#000000",
    "brand-white": "#FFFFFF",
    "teal-50": "#EBF7F7",
    "teal-100": "#D6EEEF",
    "teal-200": "#A3DADB",
    "teal-300": "#70C5C8",
    "teal-400": "#38AEB2",
    "teal-500": "#00979C",
    "teal-600": "#008085",
    "teal-700": "#006A6D",
    "teal-800": "#004C4E",
    "teal-900": "#002A2C",
    "yellow-50": "#FEF8E6",
    "yellow-100": "#FEF1CC",
    "yellow-200": "#FDE499",
    "yellow-500": "#F9BB00",
    "yellow-600": "#D9A300",
    "yellow-700": "#B38700",
    "ink": "#1C2122",
    "sub": "#657A7B",
    "muted": "#94A7A8",
    "line": "#DDE3E3",
    "bg": "#F4F6F6",
    "paper": "#FFFFFF",
    "success": "#008085",
    "warning": "#B38700",
    "danger": "#D8472B",
    "info": "#006A6D",
    "mascot-teal": "#1E8C86",
    "mascot-teal-mid": "#31ACA2",
    "mascot-teal-light": "#87C0B9",
    "mascot-belly": "#D9E2DC",
    "mascot-navy": "#1B2750",
    "mascot-yellow": "#FEDB3C"
}
RGB = {
    "brand-teal": [
        0,
        151,
        156
    ],
    "brand-yellow": [
        249,
        187,
        0
    ],
    "brand-black": [
        0,
        0,
        0
    ],
    "brand-white": [
        255,
        255,
        255
    ],
    "teal-50": [
        235,
        247,
        247
    ],
    "teal-100": [
        214,
        238,
        239
    ],
    "teal-200": [
        163,
        218,
        219
    ],
    "teal-300": [
        112,
        197,
        200
    ],
    "teal-400": [
        56,
        174,
        178
    ],
    "teal-500": [
        0,
        151,
        156
    ],
    "teal-600": [
        0,
        128,
        133
    ],
    "teal-700": [
        0,
        106,
        109
    ],
    "teal-800": [
        0,
        76,
        78
    ],
    "teal-900": [
        0,
        42,
        44
    ],
    "yellow-50": [
        254,
        248,
        230
    ],
    "yellow-100": [
        254,
        241,
        204
    ],
    "yellow-200": [
        253,
        228,
        153
    ],
    "yellow-500": [
        249,
        187,
        0
    ],
    "yellow-600": [
        217,
        163,
        0
    ],
    "yellow-700": [
        179,
        135,
        0
    ],
    "ink": [
        28,
        33,
        34
    ],
    "sub": [
        101,
        122,
        123
    ],
    "muted": [
        148,
        167,
        168
    ],
    "line": [
        221,
        227,
        227
    ],
    "bg": [
        244,
        246,
        246
    ],
    "paper": [
        255,
        255,
        255
    ],
    "success": [
        0,
        128,
        133
    ],
    "warning": [
        179,
        135,
        0
    ],
    "danger": [
        216,
        71,
        43
    ],
    "info": [
        0,
        106,
        109
    ],
    "mascot-teal": [
        30,
        140,
        134
    ],
    "mascot-teal-mid": [
        49,
        172,
        162
    ],
    "mascot-teal-light": [
        135,
        192,
        185
    ],
    "mascot-belly": [
        217,
        226,
        220
    ],
    "mascot-navy": [
        27,
        39,
        80
    ],
    "mascot-yellow": [
        254,
        219,
        60
    ]
}
FONT_SANS = 'Zen Kaku Gothic New'
FONT_MONO = 'IBM Plex Mono'
FONT_DISPLAY = 'Poppins'
FONT_SANS_OFFICE_FALLBACK = 'Yu Gothic'
SCALE_PX = {"xs": 12, "sm": 14, "base": 16, "md": 18, "lg": 20, "xl": 24, "2xl": 30, "3xl": 36, "4xl": 48, "5xl": 64}
SPACE_PX = {"1": 4, "2": 8, "3": 12, "4": 16, "5": 20, "6": 24, "8": 32, "10": 40, "12": 48, "16": 64, "20": 80, "24": 96, "32": 128}
RADIUS_PX = {"none": 0, "sm": 4, "md": 8, "lg": 16, "pill": 999}
CMYK = {"brand-teal": [85, 8, 39, 10], "brand-yellow": [0, 32, 100, 0], "brand-black": [0, 0, 0, 100], "brand-white": [0, 0, 0, 0]}
